In [1]:
import sys
print(sys.version)
print(sys.path)

3.9.12 (main, Apr  5 2022, 01:53:17) 
[Clang 12.0.0 ]
['/Users/shenalfernando/Documents/projects/Applied AI/Tut 2', '/opt/anaconda3/lib/python39.zip', '/opt/anaconda3/lib/python3.9', '/opt/anaconda3/lib/python3.9/lib-dynload', '', '/opt/anaconda3/lib/python3.9/site-packages', '/opt/anaconda3/lib/python3.9/site-packages/aeosa']


In [3]:
import sys
print(f'Article is sing python version {sys.version} on this machine')

Article is sing python version 3.9.12 (main, Apr  5 2022, 01:53:17) 
[Clang 12.0.0 ] on this machine


In [4]:
print('hello')

hello


In [5]:
pwd

'/Users/shenalfernando/Documents/projects/Applied AI/Tut 2'

In [6]:
lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%

In [7]:
print(1+1)

2


In [8]:
print(2+3)

5


In [9]:
print(1==0)
print(False == 0)
print(True == 8)
print("hello" == 'hello')

False
True
False
True


In [10]:
print('6COCS020W ' + 'Applied '+ 'AI' + '!'*3)
print('applied ai'.upper())
print(len('Artificial Intelligence'))

6COCS020W Applied AI!!!
APPLIED AI
23


In [11]:
s = 'Westminster Uni has a great selection of options!'
print(s)
s = 25
print(s)

Westminster Uni has a great selection of options!
25


In [13]:
s = 'Applied AI'
print(s.find('AI'))
help(s.find)

8
Help on built-in function find:

find(...) method of builtins.str instance
    S.find(sub[, start[, end]]) -> int
    
    Return the lowest index in S where substring sub is found,
    such that sub is contained within S[start:end].  Optional
    arguments start and end are interpreted as in slice notation.
    
    Return -1 on failure.



In [14]:
s = 'ai'
help(s.lower)

Help on built-in function lower:

lower() method of builtins.str instance
    Return a copy of the string converted to lowercase.



In [15]:
colours = ['red', 'orange', 'yellow', 'green', 'blue']
print(colours[0])
print(colours[-1])
colours[0] = 'purple'
print(colours[0])
print(colours[2:4])

red
blue
purple
['yellow', 'green']


In [16]:
point = (2,3)
x,y = point
print(f'Point({x}, {y})')

Point(2, 3)


In [18]:
room1 = {'chair', 'table', 'spoon'}
room2 = {'chair', 'bed', 'plate', 'spoon'}
print(room1, room2)
print('spoon' in room1)
print(room1.intersection(room2))
print(room1.union(room2))

{'chair', 'table', 'spoon'} {'bed', 'chair', 'spoon', 'plate'}
True
{'chair', 'spoon'}
{'bed', 'chair', 'plate', 'spoon', 'table'}


In [21]:
order = {'apples': 5, 'oranges':3, 'lemons':2}
print(order['oranges'])
order['oranges'] += 5
print(f"I ordered {order['oranges']} oranges")
print(order.keys(), order.values())

3
I ordered 8 oranges
dict_keys(['apples', 'oranges', 'lemons']) dict_values([5, 8, 2])


In [22]:
a = input("Enter your name: ")
print(f"Hello {a}")

Enter your name: Shenal
Hello Shenal


In [23]:
f = open('file.txt', 'r')
print(f.read())

The rain fell on the car. The rain fell on the ground.



In [24]:
for n in range(10):
        print(n)

0
1
2
3
4
5
6
7
8
9


In [25]:
for n in range(3,10):
    print(n)

3
4
5
6
7
8
9


In [26]:
for n in range(3,10,2):
    print(n)

3
5
7
9


In [30]:
evens = [x for x in range(10) if x%2 == 0]
print(evens)

[0, 2, 4, 6, 8]


In [33]:
squared_odd = [ x*x for x in range(10) if x%2 == 1]
print(squared_odd)

[1, 9, 25, 49, 81]


In [34]:
class FruitShop:
    def __init__(self, name, fruitPrices):
        """
        name: Name of the fruit shop
        fruitPrices: Dictionary with keys as fruit
        {'apples': 2.00, 'orange': 1.50, 'pears': '1.75'}
        """
        self.fruitPrices = fruitPrices
        self.name = name
        print('Welcome to %s fruit shop', (name))
        
    def getCostPerPound(self, fruit):
        """
        fruit: Fruit string returns cost of 'fruit'
        is in our inventory or None otherwise
        """
        if fruit not in self.fruitPrices:
            return none
        return self.fruitPrices[fruit]
    
    def getPriceOfOrder(self, orderList):
        """
        orderList: list of (fruit, numPounds) tuples
        returns cost of the orderList, only including the values of
        fruits that this fruit shp has
        """
        totalCost = 0.0
        for fruit, numPounds in orderList:
            costPerPound = self.getCostPerPound(fruit)
            if costPerPound != None:
                totalCost += numPounds * costPerPound
        return totalCost
    
    def getName(self):
        return self.name

In [38]:
shopName = 'the Berkeley Bowl'
fruitPrices = {'apples': 1.00, 'oranges': 1.50, 'pears': 1.75}
berkeleyShop = FruitShop(shopName, fruitPrices)
applePrice = berkeleyShop.getCostPerPound('apples')
print(applePrice)
print('Apples cost $%.2f at %s.' % (applePrice, shopName))

otherName = 'the stanford Mall'
otherFruitPrices = { 'kiwis': 6.00, 'apples': 4.50, 'peaches': 8.75}
otherFruitShop = FruitShop(otherName,otherFruitPrices)
otherPrice = otherFruitShop.getCostPerPound('apples')
print(otherPrice)
print('Apples cost $%.2f at %s.' % (otherPrice, otherName))
print("My, that's expensive!")

Welcome to %s fruit shop the Berkeley Bowl
1.0
Apples cost $1.00 at the Berkeley Bowl.
Welcome to %s fruit shop the stanford Mall
4.5
Apples cost $4.50 at the stanford Mall.
My, that's expensive!


In [39]:
import numpy as np

In [41]:
a = np.arange(3)
print(a)

[0 1 2]


In [43]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [44]:
a**2

array([0, 1, 4])

In [45]:
c**2

array([[[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]],

       [[144, 169, 196, 225],
        [256, 289, 324, 361],
        [400, 441, 484, 529]]])